---
title:            whoami
author:           ℵancym
first published:  2015-11-10
updated:          2015-11-10
feedback:         https://github.com/nancym/whoami/issues
---

= whoami
:hide-uri-scheme:

First, I am a privacy nut so it's always hard for me to figure out what to publicly say about myself, but here goes.

I am a nerd and the title of this page is a reference to the Unix https://en.wikipedia.org/wiki/Whoami[`whoami` command]. What kind of nerd am I? Mainly a mathematics nerd. I :purple_heart: :blue_heart: :green_heart:  :heart: math and teaching, and when I was young my goal was to teach math at a small liberal arts college. I achieved that goal and was shocked to discover that that wasn't really what I wanted to do. I shifted to technical writing, which seemed to me to be a way I could still teach nerdy things but not have to deal with the low pay and frustrationsfootnote:[My teaching frustrations were mainly related to grading.] of teaching. I still, many years later, think that my path is to teach nerdy things.

Another part of me that may help you to understand what I do on the internet is that I am a natural born evangelist. When I'm enthusiastic about something I do what I can to get other people to join in. I do this because I think it will be good for:

. you,
. the world, and
. the thing I'm evangelizing.

Here are some of the things I've been evangelistic about:

* Usenet and NNTP
* Free/Libre Open Source Software (FLOSS) and Open Standards
* Public communication tools and services that do not require you to give any https://en.wikipedia.org/wiki/Personally_identifiable_information[personally identifiable information (PII)], such as your real name or real birth date.
* IMAP
* Pine (**P**OP, **I**MAP, **N**NTP, & **E**SMTP client), which was renamed Alpine
* Antirealismfootnote:[I was very interested in the realism/antirealism debate in philosophy of science, especially philosophy of physics. These issues are different, but also interesting to me, in philosphy of mathematics and philosophy of religion.] in academic philosophy
* Privacy and security
* https://en.wikipedia.org/wiki/AsciiDoc[AsciiDoc markup language], Git, and GitHub


I'm still enthusiastic about most of the things on this list (but not Usenet :scream:), and
the last two bullets are what I'm most into at the moment (2015).

NOTE: I'm not evangelistic about everything I care about. For example, I've been lacto-ovo vegetarian for more than 30 years and I don't think I have ever suggested that someone else become vegetarian.

I took a Myers-Briggs test on the internet and it said I had an https://en.wikipedia.org/wiki/ENFP[ENFP (Extraversion, Intuition, Feeling, Perception)] or 
"`Inspirer`" personality type.footnote:[An ENFP is called a 
http://www.16personalities.com/enfp-personality[Campaigner],
Champion,
http://personalitypage.com/ENFP.html[Creative Idealist],
or
http://personalitypage.com/ENFP.html[Inspirer].]
This rang true to me, which is why I'm mentioning it here. Over the years, random internet people who don't know me IRL have accused me of promoting something for financial gain, but that's never been the case. Instead I was trying to make the world (or the internet) a better place. My guess is that those random accusers were not ENFPs and do not understand ENFPs:smiley:.

== whereami

On the internet, I'm a lot of places, including:

* https://twitter.com/nm
* http://nancym.tumblr.com
* http://deflexion.com (old, needs to be updated)
* http://www.ii.com (really old, really needs to be updated)

If a public internet place requires a real name, real birthday, or any https://en.wikipedia.org/wiki/Personally_identifiable_information[PII], you can be pretty sure I'm not there.

On planet earth, I'm a https://en.wikipedia.org/wiki/Digital_nomad[digital nomad] and have lived a lot of places.

****
sidebar test
****

now outside sidebar
